# Generated by Django 5.2.4 on 2025-07-10 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminaloffenselink',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='criminaloffenselink',
            name='object_id',
        ),
        migrations.AddField(
            model_name='criminaloffenselink',
            name='federal_offense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criminals.federaloffense'),
        ),
        migrations.AddField(
            model_name='criminaloffenselink',
            name='vacode_offense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criminals.vacodeoffense'),
        ),
        migrations.AlterField(
            model_name='federaloffense',
            name='offense_class',
            field=models.CharField(choices=[('A', 'Class A'), ('B', 'Class B'), ('C', 'Class C'), ('D', 'Class D'), ('E', 'Class E'), ('NA', 'Infraction')], max_length=2),
        ),
        migrations.AlterField(
            model_name='vacodeoffense',
            name='offense_class',
            field=models.CharField(choices=[('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('NA', 'Infraction')], max_length=2),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
